/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Game from "./script/game/Game"
import WidgetMgr from "./script/game/ctrl/WidgetMgr"
import LoadingView from "./script/add/Page/LoadingView"
import GameTest from "./script/game/GameTest"
import AutoShake from "./script/game/ctrl/AutoShake"
import AutoScale from "./script/game/ctrl/AutoScale"
import Loading from "./script/game/Loading"
import AdvLoadMgr from "./script/game/ctrl/AdvLoadMgr"
import BannerPopup from "./script/game/ui/popup/BannerPopup"
import Flow from "./script/game/ui/popup/Flow"
import Finish from "./script/game/ui/popup/Finish"
import MoreGamePopup from "./script/game/ui/popup/MoreGamePopup"
import NativeFlow from "./script/game/ui/popup/NativeFlow"
import InsertPopup from "./script/game/ui/popup/InsertPopup"
import ExitPopup from "./script/game/ui/popup/ExitPopup"
import ExitBtnPopup from "./script/game/ui/popup/ExitBtnPopup"
import FullScenePopup from "./script/game/ui/popup/FullScenePopup"
import NewGameExitPopup from "./script/game/ui/popup/NewGameExitPopup"
import ScrollPopup from "./script/game/ui/popup/ScrollPopup"
import FakeLoadingPopup from "./script/game/ui/popup/FakeLoadingPopup"
import NewFullScenePopup from "./script/game/ui/popup/NewFullScenePopup"
import RewardNavAdPopup from "./script/game/ui/popup/RewardNavAdPopup"
import CaptureMgr from "./script/game/ui/popup/CaptureMgr"
import Finger from "./script/game/ui/popup/Finger"
import Waiting from "./script/game/ui/popup/Waiting"
import ClickPopup from "./script/game/ui/popup/ClickPopup"
import Modal from "./script/game/ui/popup/Modal"
import AdFullView from "./script/add/Page/AdFullView"
import AdView from "./script/add/Page/AdView"
import TweenType from "./script/add/UIFrame/TweenType"
import DaliyTaskView from "./script/add/Page/DaliyTaskView"
import NativeInsert from "./script/add/gameMgr/NativeInsert"
import DelineReward from "./script/add/Page/DelineReward"
import EggsClue from "./script/add/Page/EggsClue"
import EggsView from "./script/add/Page/EggsView"
import ExtraWeapon from "./script/add/Page/ExtraWeapon"
import FightBoxView from "./script/add/Page/FightBoxView"
import GameOverViewEnd from "./script/add/Page/GameOverViewEnd"
import PlatPosOffect from "./script/add/UIFrame/PlatPosOffect"
import GameOverFirst from "./script/add/Page/GameOverFirst"
import GameOverView from "./script/add/Page/GameOverView"
import GameView from "./script/add/Page/GameView"
import DragCorl from "./script/add/ctrol/DragCorl"
import GetDiamView from "./script/add/Page/GetDiamView"
import GetEggsCube from "./script/add/Page/GetEggsCube"
import GetGoldView from "./script/add/Page/GetGoldView"
import GetPowerView from "./script/add/Page/GetPowerView"
import GetRewardView from "./script/add/Page/GetRewardView"
import GoldFingerView from "./script/add/Page/GoldFingerView"
import ManicureVipView from "./script/add/Page/ManicureVipView"
import MisGetDaim from "./script/add/Page/MisGetDaim"
import OpenBoxView from "./script/add/Page/OpenBoxView"
import PopupView from "./script/add/Page/PopupView"
import ReadView from "./script/add/Page/ReadView"
import TeachBtn from "./script/add/teach/TeachBtn"
import PlatHint from "./script/add/UIFrame/PlatHint"
import RebornView from "./script/add/Page/RebornView"
import SelectLevelModel from "./script/add/Page/SelectLevelModel"
import SensibilitySettingView from "./script/add/Page/SensibilitySettingView"
import SettingView from "./script/add/Page/SettingView"
import SginView from "./script/add/Page/SginView"
import ShareView from "./script/add/Page/ShareView"
import SkinView from "./script/add/Page/SkinView"
import TeachView from "./script/add/Page/TeachView"
import ToolsView from "./script/add/Page/ToolsView"
import TrainView from "./script/add/Page/TrainView"
import TrainWantedView from "./script/add/Page/TrainWantedView"
import TryUseSkinView from "./script/add/Page/TryUseSkinView"
import TTGetItemView from "./script/add/Page/TTGetItemView"
import TTOpenBoxView from "./script/add/Page/TTOpenBoxView"
import TurntableView from "./script/add/Page/TurntableView"
import SettingPopup from "./script/game/ui/popup/SettingPopup"
import Tips from "./script/game/ui/popup/Tips"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/game/Game.js",Game);
		reg("script/game/ctrl/WidgetMgr.js",WidgetMgr);
		reg("script/add/Page/LoadingView.js",LoadingView);
		reg("script/game/GameTest.js",GameTest);
		reg("script/game/ctrl/AutoShake.js",AutoShake);
		reg("script/game/ctrl/AutoScale.js",AutoScale);
		reg("script/game/Loading.js",Loading);
		reg("script/game/ctrl/AdvLoadMgr.js",AdvLoadMgr);
		reg("script/game/ui/popup/BannerPopup.js",BannerPopup);
		reg("script/game/ui/popup/Flow.js",Flow);
		reg("script/game/ui/popup/Finish.js",Finish);
		reg("script/game/ui/popup/MoreGamePopup.js",MoreGamePopup);
		reg("script/game/ui/popup/NativeFlow.js",NativeFlow);
		reg("script/game/ui/popup/InsertPopup.js",InsertPopup);
		reg("script/game/ui/popup/ExitPopup.js",ExitPopup);
		reg("script/game/ui/popup/ExitBtnPopup.js",ExitBtnPopup);
		reg("script/game/ui/popup/FullScenePopup.js",FullScenePopup);
		reg("script/game/ui/popup/NewGameExitPopup.js",NewGameExitPopup);
		reg("script/game/ui/popup/ScrollPopup.js",ScrollPopup);
		reg("script/game/ui/popup/FakeLoadingPopup.js",FakeLoadingPopup);
		reg("script/game/ui/popup/NewFullScenePopup.js",NewFullScenePopup);
		reg("script/game/ui/popup/RewardNavAdPopup.js",RewardNavAdPopup);
		reg("script/game/ui/popup/CaptureMgr.js",CaptureMgr);
		reg("script/game/ui/popup/Finger.js",Finger);
		reg("script/game/ui/popup/Waiting.js",Waiting);
		reg("script/game/ui/popup/ClickPopup.js",ClickPopup);
		reg("script/game/ui/popup/Modal.js",Modal);
		reg("script/add/Page/AdFullView.js",AdFullView);
		reg("script/add/Page/AdView.js",AdView);
		reg("script/add/UIFrame/TweenType.js",TweenType);
		reg("script/add/Page/DaliyTaskView.js",DaliyTaskView);
		reg("script/add/gameMgr/NativeInsert.js",NativeInsert);
		reg("script/add/Page/DelineReward.js",DelineReward);
		reg("script/add/Page/EggsClue.js",EggsClue);
		reg("script/add/Page/EggsView.js",EggsView);
		reg("script/add/Page/ExtraWeapon.js",ExtraWeapon);
		reg("script/add/Page/FightBoxView.js",FightBoxView);
		reg("script/add/Page/GameOverViewEnd.js",GameOverViewEnd);
		reg("script/add/UIFrame/PlatPosOffect.js",PlatPosOffect);
		reg("script/add/Page/GameOverFirst.js",GameOverFirst);
		reg("script/add/Page/GameOverView.js",GameOverView);
		reg("script/add/Page/GameView.js",GameView);
		reg("script/add/ctrol/DragCorl.js",DragCorl);
		reg("script/add/Page/GetDiamView.js",GetDiamView);
		reg("script/add/Page/GetEggsCube.js",GetEggsCube);
		reg("script/add/Page/GetGoldView.js",GetGoldView);
		reg("script/add/Page/GetPowerView.js",GetPowerView);
		reg("script/add/Page/GetRewardView.js",GetRewardView);
		reg("script/add/Page/GoldFingerView.js",GoldFingerView);
		reg("script/add/Page/ManicureVipView.js",ManicureVipView);
		reg("script/add/Page/MisGetDaim.js",MisGetDaim);
		reg("script/add/Page/OpenBoxView.js",OpenBoxView);
		reg("script/add/Page/PopupView.js",PopupView);
		reg("script/add/Page/ReadView.js",ReadView);
		reg("script/add/teach/TeachBtn.js",TeachBtn);
		reg("script/add/UIFrame/PlatHint.js",PlatHint);
		reg("script/add/Page/RebornView.js",RebornView);
		reg("script/add/Page/SelectLevelModel.js",SelectLevelModel);
		reg("script/add/Page/SensibilitySettingView.js",SensibilitySettingView);
		reg("script/add/Page/SettingView.js",SettingView);
		reg("script/add/Page/SginView.js",SginView);
		reg("script/add/Page/ShareView.js",ShareView);
		reg("script/add/Page/SkinView.js",SkinView);
		reg("script/add/Page/TeachView.js",TeachView);
		reg("script/add/Page/ToolsView.js",ToolsView);
		reg("script/add/Page/TrainView.js",TrainView);
		reg("script/add/Page/TrainWantedView.js",TrainWantedView);
		reg("script/add/Page/TryUseSkinView.js",TryUseSkinView);
		reg("script/add/Page/TTGetItemView.js",TTGetItemView);
		reg("script/add/Page/TTOpenBoxView.js",TTOpenBoxView);
		reg("script/add/Page/TurntableView.js",TurntableView);
		reg("script/game/ui/popup/SettingPopup.js",SettingPopup);
		reg("script/game/ui/popup/Tips.js",Tips);
    }
}
GameConfig.width = 750;
GameConfig.height = 1344;
GameConfig.scaleMode ="fixedheight";
GameConfig.screenMode = "vertical";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "loading/LoadingScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
